### ISSUE TITLE
Error with basic examples

### ISSUE THREAD

**Issue by Balinus** [slayton/matlab-xkcdify#1]
Got this error by running the provided example.

??? Undefined function or method 'filtfilt' for input arguments of type 'double'.

Error in ==> xkcdify>smooth at 361
    v = filtfilt(a, [1 a-1], [ ones(nPad ,1) \* v(1); v; ones(nPad,1) \* v(end) ]);

Error in ==> xkcdify>upSampleAndJitter at 227
    x = x + smooth( generateNoise(n) .\* rand(n,1) .\* jx )';

Error in ==> xkcdify>cartoonifyLine at 167
        [xpts, ypts] = upSampleAndJitter(xpts, ypts, xJitter, yJitter);

Error in ==> xkcdify>operareOnChildren at 121
                cartoonifyLine(c, ax);

Error in ==> xkcdify at 48
        operareOnChildren(axChildren, axHandle);

**Comment by slayton** [comment]
Thanks for the report, `filtfilt` is available in the signal processing toolbox. I forgot that this depended on that

**Comment by Balinus** [comment]
ah, too bad! :)

Thanks!

**Comment by RoyiAvital** [comment]
Hi,
Looks Awesome!

Does it work on R2016b / R2017a?

Thank You.
